port: 8080
spring:
    application:
        name: ShoeStoreBoot
    datasource:
        url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=ShoeStore
        username: sa
        password: nguyenmanh2707
    jpa:
        open-in-view: true
        show-sql: true
